[build]
command = "next build && next export"
publish = "out"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[dev]
framework = "#static"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@netlify/plugin-local-install-core"
