[build]
<<<<<<< HEAD
command = "npm run build && npm run export"
publish = "out"
=======
command = "npm run build"
publish = ".next"
ignore = "if [ $CACHED_COMMIT_REF == $COMMIT_REF ]; then (exit 1); else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../..; fi;"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[dev]
framework = "#static"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@netlify/plugin-local-install-core"
>>>>>>> c0e6a4a82e67f23479598bbd8a81979db755924e
