[build]
command = "next build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"
NODE_VERSION = "17"

[dev]
framework = "#static"

[[plugins]]
package = "@netlify/plugin-local-install-core"
